In [4]:
import numpy as np
import random

In [5]:
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 2, 3],
        [2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]],

       [[2, 3, 3, 1],
        [1, 3, 1, 2],
        [3, 1, 3, 1],
        [2, 3, 1, 2]]])

In [6]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [8]:
2**32-1

4294967295

In [9]:
np.random.rand(3,3)

array([[0.13145815, 0.41366737, 0.77872881],
       [0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327]])

In [10]:
np.random.randn(3,3)

array([[ 0.67893119, -1.91355421, -0.94245806],
       [-1.74554298, -1.02094527, -0.16206903],
       [-0.6579709 ,  0.42211306,  0.62402334]])

In [11]:
x=[1,2,3,4]
np.random.choice(x)

1

In [12]:
for i in range(20):
    print(np.random.choice(x))

1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3
4
1
1
1


In [13]:
np.random.permutation(x)

array([2, 4, 3, 1])

In [14]:
np.random.permutation(x)

array([1, 3, 4, 2])